openapi: 3.0.3
info:
  title: "Multipart form data API"
  description: An api that uses multipart/form-data as request type
  version: 1.0.0

servers:
  - url: "http://other-endpoint.com/api/v1"

paths:
  /type-mapping:
    post:
      tags:
        - Type Mapping
      operationId: PostTheData
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MultipartRequestBody'
      responses:
        "204":
          description: "Data uploaded"
        "400":
          description: "Invalid ID supplied"

components:
  schemas:
    SomeDateTime:
      type: string
      format: date-time
    BinaryStringFile:
      type: string
      format: binary
    UserId:
      type: string
      format: uuid
    YearMonth:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50

    MultipartRequestBody:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        dateTime:
          $ref: '#/components/schemas/SomeDateTime'
        binaryStringFile:
          $ref: '#/components/schemas/BinaryStringFile'
        yearMonth:
          $ref: '#/components/schemas/YearMonth'


